### ISSUE TITLE
It should not be possible to mix object files with different -cheri-cap-table-abi=...

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/lld#20]
This could lead to very strange crashes at runtime. Not sure how best to store this metadata, maybe a ELF note?

**Comment by bsdjhb** [comment]
Are there a couple of spare bits in ef_flags in the ELF header?  Actually, you could make these separate ABIs for now.  EF_MIPS_ABI isn't a bit mask, it just has separate values, so you could use the existing 0xc value for the original CheriABI and use values 'd', 'e', etc. for other values if we think there will only be 2 or 4.  We can always revisit and do an actual NOTE in the future, but if we don't need it, using EF_MIPS_ABI is a lot simpler.

**Comment by arichardson** [comment]
In terms of implementation an e_flags abi value would certainly be the easiest but I believe we check that in the kernel so it will refuse to load those binaries as CheriABI ones? 

Some other options might be to reuse some empty space in the .MIPS.abiflags/.MIPS.options sections or just dump a string in .comment.

**Comment by bsdjhb** [comment]
We could whitelist more ABI values, but yes one of the latter notes is probably more correct.  It is more like soft-float vs hard-float, so however that is handled is probably the model to follow.
